name: Build

on:
  push:
    branches:
      - master
      - gmod-colors

jobs:
  now:
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: pwsh
        run: |
          python build.py
          copy src/rndx_compiled.lua C:\rndx.lua

      - name: Set Unix Timestamp
        id: time
        shell: pwsh
        run: |
          $timestamp = Get-Date -UFormat %s
          echo "timestamp=$timestamp" >> $env:GITHUB_OUTPUT

      - name: Release (master)
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.time.outputs.timestamp }}
          name: "RNDX ${{ steps.time.outputs.timestamp }}"
          allowUpdates: true
          artifacts: C:\rndx.lua
          makeLatest: true

      - name: Release (gmod-colors)
        if: github.ref == 'refs/heads/gmod-colors'
        uses: ncipollo/release-action@v1
        with:
          tag: gmod-colors-${{ steps.time.outputs.timestamp }}
          name: "RNDX (gmod-colors) ${{ steps.time.outputs.timestamp }}"
          allowUpdates: true
          artifacts: C:\rndx.lua
          prerelease: true
          makeLatest: false
